# Generated by Django 4.1.7 on 2023-05-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Часто задаваемые вопросы',
            },
        ),
    ]
